### ISSUE TITLE
empty output dir

### ISSUE THREAD

**Issue by FAhtisham** [deeprob/pssmpro#1]
Hi,

By running your script, the command line shows that the profiles have been generated but the output dir is empty.

`from pssmpro.features import create_pssm_profile
protein_sequence_file = "EC/EC.csv"
species="_EC"
output_dir = "./pssm_profiles"
if not os.path.exists(output_dir+species):
    os.makedirs(output_dir+species)
blast_db_prefix = "/uniref_db/uniref50db"
psiblast_executable_path = "/usr/bin/psiblast"
number_of_cores = 8
create_pssm_profile(protein_sequence_file, output_dir, psiblast_executable_path,blast_db_prefix, number_of_cores)`

**Comment by FAhtisham** [comment]
Somehow cmd logs show this : 

Command line argument error: Argument "query". File is not accessible:

**Comment by deeprob** [comment]
Hi, can you check 
1) if the blast_db_prefix is correct? It might be possible that the prefix is "/path/to/uniref_db/uniref50"
2) if the prefix is correct, then is a temporary file being created in your PWD whose filename is the same as the name of the first protein in the protein_sequence_file?

**Comment by FAhtisham** [comment]
Hey,

Just solved the problem.

The error was related to the directories, for some reason, it does not pick up the output dir correctly. 

But it works correctly if I allow the tool to save the output profiles in CWD. 

Thanks for your response.

**Comment by deeprob** [comment]
Nice to hear that you have solved it!
